services:
  postgres:
    image: postgres:17
    container_name: orders-postgres
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_password
    ports:
      - "5432:5432"
    volumes:
      - orders_pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: orders-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  orders_pgdata: