// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderPickingService.Domain.Enums;
using OrderPickingService.Infrastructure.Database;

#nullable disable

namespace OrderPickingService.Infrastructure.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260319112601_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "order_status", new[] { "available", "picked", "picking", "reserved" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "picking_status", new[] { "canceled", "completed", "in_progress" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderPickingService.Infrastructure.Database.Entities.Order.OrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<OrderStatus>("OrderStatus")
                        .HasColumnType("order_status")
                        .HasColumnName("order_status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.ToTable("orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            ExternalId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            OrderStatus = OrderStatus.Available
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            ExternalId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsDeleted = false,
                            OrderStatus = OrderStatus.Available
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            ExternalId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsDeleted = false,
                            OrderStatus = OrderStatus.Available
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            ExternalId = new Guid("44444444-4444-4444-4444-444444444444"),
                            IsDeleted = false,
                            OrderStatus = OrderStatus.Available
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            ExternalId = new Guid("55555555-5555-5555-5555-555555555555"),
                            IsDeleted = false,
                            OrderStatus = OrderStatus.Available
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            ExternalId = new Guid("66666666-6666-6666-6666-666666666666"),
                            IsDeleted = false,
                            OrderStatus = OrderStatus.Available
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            ExternalId = new Guid("77777777-7777-7777-7777-777777777777"),
                            IsDeleted = false,
                            OrderStatus = OrderStatus.Available
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            ExternalId = new Guid("88888888-8888-8888-8888-888888888888"),
                            IsDeleted = false,
                            OrderStatus = OrderStatus.Available
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            ExternalId = new Guid("99999999-9999-9999-9999-999999999999"),
                            IsDeleted = false,
                            OrderStatus = OrderStatus.Available
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            ExternalId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsDeleted = false,
                            OrderStatus = OrderStatus.Available
                        });
                });

            modelBuilder.Entity("OrderPickingService.Infrastructure.Database.Entities.Order.OrderItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_external_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_sku");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.ToTable("order_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderItems_Price_NonNegative", "price >= 0");

                            t.HasCheckConstraint("CK_OrderItems_Quantity_Positive", "quantity > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Молочные продукты",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 1L,
                            Price = 119.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000003"),
                            ProductName = "Молоко",
                            ProductSku = "DAIRY-0001",
                            Quantity = 2L
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Хлеб и выпечка",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 1L,
                            Price = 54.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000006"),
                            ProductName = "Хлеб белый",
                            ProductSku = "BAKERY-0001",
                            Quantity = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Овощи",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 2L,
                            Price = 79.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000010"),
                            ProductName = "Картофель",
                            ProductSku = "VEGET-0001",
                            Quantity = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Овощи",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 2L,
                            Price = 159.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000011"),
                            ProductName = "Огурцы",
                            ProductSku = "VEGET-0002",
                            Quantity = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Фрукты",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 2L,
                            Price = 149.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000008"),
                            ProductName = "Яблоки",
                            ProductSku = "FRUITS-0001",
                            Quantity = 2L
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Напитки",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 3L,
                            Price = 69.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000022"),
                            ProductName = "Минеральная вода",
                            ProductSku = "DRINKS-0001",
                            Quantity = 6L
                        },
                        new
                        {
                            Id = 7L,
                            Category = "Напитки",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 3L,
                            Price = 149.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000023"),
                            ProductName = "Апельсиновый сок",
                            ProductSku = "DRINKS-0002",
                            Quantity = 2L
                        },
                        new
                        {
                            Id = 8L,
                            Category = "Бытовая химия",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 4L,
                            Price = 599.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000012"),
                            ProductName = "Гель для стирки",
                            ProductSku = "HOME-0001",
                            Quantity = 1L
                        },
                        new
                        {
                            Id = 9L,
                            Category = "Бытовая химия",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 4L,
                            Price = 249.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000013"),
                            ProductName = "Средство для посуды",
                            ProductSku = "HOME-0002",
                            Quantity = 2L
                        },
                        new
                        {
                            Id = 10L,
                            Category = "Товары для дома",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 4L,
                            Price = 129.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000014"),
                            ProductName = "Бумажные полотенца",
                            ProductSku = "HOME-0003",
                            Quantity = 3L
                        },
                        new
                        {
                            Id = 11L,
                            Category = "Мясо и птица",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 5L,
                            Price = 329.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000020"),
                            ProductName = "Куриное филе",
                            ProductSku = "MEAT-0001",
                            Quantity = 2L
                        },
                        new
                        {
                            Id = 12L,
                            Category = "Мясо и птица",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 5L,
                            Price = 289.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000021"),
                            ProductName = "Фарш говяжий",
                            ProductSku = "MEAT-0002",
                            Quantity = 1L
                        },
                        new
                        {
                            Id = 13L,
                            Category = "Молочные продукты",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 6L,
                            Price = 219.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000004"),
                            ProductName = "Сыр",
                            ProductSku = "DAIRY-0002",
                            Quantity = 3L
                        },
                        new
                        {
                            Id = 14L,
                            Category = "Молочные продукты",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 6L,
                            Price = 89.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000005"),
                            ProductName = "Йогурт",
                            ProductSku = "DAIRY-0003",
                            Quantity = 5L
                        },
                        new
                        {
                            Id = 15L,
                            Category = "Автомобильные товары",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 7L,
                            Price = 1250.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000001"),
                            ProductName = "Машинное масло",
                            ProductSku = "AUTO-0001",
                            Quantity = 1L
                        },
                        new
                        {
                            Id = 16L,
                            Category = "Автомобильные товары",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 7L,
                            Price = 349.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000002"),
                            ProductName = "Омыватель стекла",
                            ProductSku = "AUTO-0002",
                            Quantity = 2L
                        },
                        new
                        {
                            Id = 17L,
                            Category = "Электроника",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 8L,
                            Price = 2999.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000017"),
                            ProductName = "Наушники беспроводные",
                            ProductSku = "ELECTRO-0001",
                            Quantity = 1L
                        },
                        new
                        {
                            Id = 18L,
                            Category = "Электроника",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 8L,
                            Price = 299.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000018"),
                            ProductName = "Кабель USB-C",
                            ProductSku = "ELECTRO-0002",
                            Quantity = 3L
                        },
                        new
                        {
                            Id = 19L,
                            Category = "Парфюмерия",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 9L,
                            Price = 3499.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000015"),
                            ProductName = "Духи",
                            ProductSku = "BEAUTY-0001",
                            Quantity = 1L
                        },
                        new
                        {
                            Id = 20L,
                            Category = "Уход за волосами",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 9L,
                            Price = 389.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000016"),
                            ProductName = "Шампунь",
                            ProductSku = "BEAUTY-0002",
                            Quantity = 2L
                        },
                        new
                        {
                            Id = 21L,
                            Category = "Шины",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 10L,
                            Price = 6590.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000019"),
                            ProductName = "Шины летние",
                            ProductSku = "TIRES-0001",
                            Quantity = 4L
                        },
                        new
                        {
                            Id = 22L,
                            Category = "Детские товары",
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            OrderId = 10L,
                            Price = 1399.00m,
                            ProductExternalId = new Guid("40000000-0000-0000-0000-000000000024"),
                            ProductName = "Подгузники",
                            ProductSku = "BABY-0001",
                            Quantity = 2L
                        });
                });

            modelBuilder.Entity("OrderPickingService.Infrastructure.Database.Entities.Picker.PickerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_pickers");

                    b.ToTable("pickers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            FirstName = "Иван",
                            IsDeleted = false,
                            LastName = "Петров"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            FirstName = "Мария",
                            IsDeleted = false,
                            LastName = "Сидорова"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            FirstName = "Алексей",
                            IsDeleted = false,
                            LastName = "Иванов"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            FirstName = "Елена",
                            IsDeleted = false,
                            LastName = "Козлова"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            FirstName = "Дмитрий",
                            IsDeleted = false,
                            LastName = "Смирнов"
                        });
                });

            modelBuilder.Entity("OrderPickingService.Infrastructure.Database.Entities.PickingSession.PickedItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<long>("OrderItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_item_id");

                    b.Property<DateTime>("PickedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("PickingSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("picking_session_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_picked_items");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("ix_picked_items_order_item_id");

                    b.HasIndex("PickingSessionId")
                        .HasDatabaseName("ix_picked_items_picking_session_id");

                    b.ToTable("picked_items", (string)null);
                });

            modelBuilder.Entity("OrderPickingService.Infrastructure.Database.Entities.PickingSession.PickingSessionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("notes");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("PickerId")
                        .HasColumnType("bigint")
                        .HasColumnName("picker_id");

                    b.Property<PickingStatus>("PickingStatus")
                        .HasColumnType("picking_status")
                        .HasColumnName("picking_status");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_picking_sessions");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_picking_sessions_order_id");

                    b.HasIndex("PickerId")
                        .HasDatabaseName("ix_picking_sessions_picker_id");

                    b.ToTable("picking_sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_PickingSessions_FinishedAt_GreaterThanOrEqualTo_StartedAt", "finished_at >= started_at");
                        });
                });

            modelBuilder.Entity("OrderPickingService.Infrastructure.Database.Entities.Order.OrderItemEntity", b =>
                {
                    b.HasOne("OrderPickingService.Infrastructure.Database.Entities.Order.OrderEntity", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderPickingService.Infrastructure.Database.Entities.PickingSession.PickedItemEntity", b =>
                {
                    b.HasOne("OrderPickingService.Infrastructure.Database.Entities.Order.OrderItemEntity", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_picked_items_order_items_order_item_id");

                    b.HasOne("OrderPickingService.Infrastructure.Database.Entities.PickingSession.PickingSessionEntity", "PickingSession")
                        .WithMany("PickedItems")
                        .HasForeignKey("PickingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_picked_items_picking_sessions_picking_session_id");

                    b.Navigation("OrderItem");

                    b.Navigation("PickingSession");
                });

            modelBuilder.Entity("OrderPickingService.Infrastructure.Database.Entities.PickingSession.PickingSessionEntity", b =>
                {
                    b.HasOne("OrderPickingService.Infrastructure.Database.Entities.Order.OrderEntity", "Order")
                        .WithMany("PickingSessions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_picking_sessions_orders_order_id");

                    b.HasOne("OrderPickingService.Infrastructure.Database.Entities.Picker.PickerEntity", "Picker")
                        .WithMany()
                        .HasForeignKey("PickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_picking_sessions_pickers_picker_id");

                    b.Navigation("Order");

                    b.Navigation("Picker");
                });

            modelBuilder.Entity("OrderPickingService.Infrastructure.Database.Entities.Order.OrderEntity", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("PickingSessions");
                });

            modelBuilder.Entity("OrderPickingService.Infrastructure.Database.Entities.PickingSession.PickingSessionEntity", b =>
                {
                    b.Navigation("PickedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
